### ISSUE TITLE
早上试用了下，发现以下问题

### ISSUE THREAD

**Issue by wesin** [ycysdf/http-downloader#1]
1. url 403, 但是文件依旧生成，并写入了错误信息。 建议：不生成文件，有回调告诉我下载失败了。
2. 文件以下载成功，继续调url下载，会再次往文件里写入新的数据，导致文件不可用。 建议：能否判断要下载文件的信息是否和url返回的一致，就不下载了，返回成功。 
3. 下载文件夹是否可以下载器里生成。 小小的建议

**Comment by ycysdf** [comment]
1. 这确实是我忽略的一个问题，我会修复
2. 目前文件已存在会直接直接覆盖，这个你可以考虑自己进行判断，毕竟这个和 Http 下载无关
3. 你指的是路径中文件夹不存，不报错而是创建文件夹吗，这个你也可以自己下载前进行判断，文件夹不存在，自己进行创建

**Comment by wesin** [comment]
2. 我的理解体验好一点么，先搞个临时文件。哪怕名字后面做点事情。不然名字一样，我也不知道你下载成功了没。
3. 虽然但是，感觉有了体感会更好

**Comment by ycysdf** [comment]
@wesin  2. 我考虑下解决方案，直接覆盖确实不妥

**Comment by ycysdf** [comment]
@wesin 我决定加上一些配置，让用户决定如何处理2与3的情况

**Comment by wesin** [comment]
哈哈。加油

**Comment by ycysdf** [comment]
@wesin 谢谢

**Comment by ycysdf** [comment]
@wesin  
1. 现在状态码错误，会直接返回错误
2. 这种情况会在下载不同文件时且断点续传时产生，需要你自己处理，断点续传校验与上次下载的Url是否相同也需要你自己处理，如果你要断点续传，你最好自己实现 DownloadDataArchiver
3. 如果保存目录路径上的文件夹不存在，默认会进行创建

**Comment by ycysdf** [comment]
v0.2.2 已发布

**Comment by ycysdf** [comment]
@wesin  2 问题本质与单文件下载器无关，要处理这个问题，你需要额外的存储一些信息，比如：这个库是我现在在写的一个下载器程序的Http 下载部分，这个下载器就在这个库的上层处理了这个问题

如果你还有问题，欢迎再提交 issue
